### ISSUE TITLE
Criação de eventos

### ISSUE THREAD

**Issue by Muzamba** [Muzamba/T1-TP1#4]
Devera se acessado somente se estiver logado, pedindo todas as infos necessarias para criar um eventos, depois sera necessario informar quantas apresentações ira ter o evento e logo depois sera necessario passar as infors das apresentações uma a uma

**Comment by Muzamba** [comment]
feita a parte da apresentação, faltando somente a parte do serviço.`5829337f55d9ad2a0d12483234b5f5414c2cc5cb`

**Comment by JoaoPedroAssis** [comment]
Tá pronto e ficou do caralho!
